version: '3'
services:
  frontend:
    image: ccj917/front-gotham:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app
  backend:
    image: ccj917/back-gotham:latest
    restart: always
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    ports:
      - "4000:4000"
    networks:
      - app
    depends_on:
      - postgres
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      pgdata: /var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - app

volumes:
  pgdata:


networks:
  app:
